version: 2
updates:
- package-ecosystem: nuget
  directories:
    - "src/Pure.RelationalSchema.Storage.PostgreSQL"
    - "src/Tests/Pure.RelationalSchema.Storage.PostgreSQL.Tests"
  schedule:
    interval: daily
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
